### ISSUE TITLE
Reduce Symfony Yaml requirement

### ISSUE THREAD

**Issue by brainwood** [hfig/MAPI#10]
I was wondering if there is any real need to need the Symfony Yaml requirement so high? I didn't thoroughly test but I tested it with a forked version with reduced Yaml version requirement and it seems to work just fine.

**Comment by hfig** [comment]
That was the release version when the library was first authored. It's not used by me in a Symfony app, so the library version dependency is kind of irrelevant. But untested too.

That version constraint doesn't support Symfony 5 is a bigger problem IMO.

Anyway submit a PR to have it changed. Note though I'd be disinclined to make a release supporting unsupported Symfony versions - so no Symfony 2.
