### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by Caroga** [hfig/MAPI#3]
Hi there! 
I'm in the need of having to parse Outlook binary .msg files with PHP to display them in twig. 
It seems that there are 2 php packages out there that should be able to do so, you are the maintainer of one of them.
I copied and pasted the code from the readme like so:
```
<?php

use Hfig\MAPI;
use Hfig\MAPI\OLE\Pear;

require __DIR__.'/../vendor/autoload.php';

// message parsing and file IO are kept separate
$messageFactory = new MAPI\MapiMessageFactory();
$documentFactory = new Pear\DocumentFactory();

$ole = $documentFactory->createFromFile('testmail.msg');
$message = $messageFactory->parseMessage($ole);

// raw properties are available from the "properties" member
echo $message->properties['subject'], "\n";

// some properties have helper methods
echo $message->getSender(), "\n";
echo $message->getBody(), "\n";

// recipients and attachments are composed objects
foreach ($message->getRecipients() as $recipient) {
    // eg "To: John Smith <john.smith@example.com>
    echo sprintf('%s: %s', $recipient->getType(), (string)$recipient), "\n";
}
```

Whenever I run it the following error occurs:
```
# php test.php 

Fatal error: Allowed memory size of 10737418240 bytes exhausted (tried to allocate 8587837472 bytes) in /srv/app/vendor/hfig/pear-ole/OLE/ChainedBlockStream.php on line 125

Call Stack:
    0.0003     361792   1. {main}() /srv/app/public/test.php:0
    0.0125     874712   2. Hfig\MAPI\OLE\Pear\DocumentFactory->createFromFile() /srv/app/public/test.php:14
    0.0164    1119328   3. OLE->read() /srv/app/vendor/hfig/mapi/src/MAPI/OLE/Pear/DocumentFactory.php:15
    0.0184    1145384   4. OLE->getStream() /srv/app/vendor/hfig/pear-ole/OLE.php:204
    0.0191    1167576   5. fopen() /srv/app/vendor/hfig/pear-ole/OLE.php:260
    0.0191    1168728   6. OLE_ChainedBlockStream->stream_open() /srv/app/vendor/hfig/pear-ole/OLE.php:260
```

I already upped the memory limit to 512mb, 1024mb and 10240mb, all with the same outcome. 
Removing the foreach also has no effect.

Would love to hear if this package actually is in working order or undergoing development, and if possible maybe a fix for the above error?

Thank you very much for all your work and I hope to hear from you.

Kind regards

**Comment by hfig** [comment]
When you call createFromFile() it literally just calls OLE::read(). This is what's crashing. So it's not this library per se with the issue.

That your code is using hfig/pear-ole (my fork of the Pear/OLE library) means you're a point release out of date. I did get the necessary fix accepted by Pear/OLE and reverted the composer manifest to use it. So I recommend updating your library. There were a few fixes in in the Pear/OLE 1.0.0RC5 release also.

Is the source message file shareable?

**Comment by greg-super** [comment]
I have just installed this and getting the same out of memory error

**Comment by hfig** [comment]
If the stack trace is the same, the problem is in <code>[Pear/OLE](https://github.com/pear/OLE)</code>, not this library. But if you can post the offending ``.msg`` file we can try to work out why.

**Comment by Caroga** [comment]
Hi, I have no clue to why I did not recieve any notificiations on this topic but.. I've went a different route and have not implemented this package. I would, as the original creator of this issue, not see any reason to keep this issue alive. 
@hfig, if you wish to keep this issue open to help @greg-super, do so. Otherwise, you could close this one.

I thank you very much for your time!
