### ISSUE TITLE
symfony/yaml requirements not enough.. 

### ISSUE THREAD

**Issue by matteocostantini** [hfig/MAPI#41]
Can you include ^6.x version? For my laravel 10 project?

**Comment by matteocostantini** [comment]
i resolve 1 conflict removing laravel/sail require.
I can't instal because composer display this
"hfig/mapi v1.2.0 requires psr/log ^1.0 -> found psr/log[1.0.0, ..., 1.1.4] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
"
Why not reveal psr/log 3.0 constraint described in composer.json with ^1.0 || ^2.0 || ^3.0 ?

**Comment by hfig** [comment]
I merged your PR
