### ISSUE TITLE
Dependency stability

### ISSUE THREAD

**Issue by redbullmarky** [hfig/MAPI#43]
Hey
Our composer package has a minimum stability of 'stable'. However, this causes issues when installing this package because:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires hfig/mapi 1.3.0 -> satisfiable by hfig/mapi[v1.3.0].
    - hfig/mapi v1.3.0 requires pear/ole ^1.0.0RC8 -> found pear/ole[v1.0.0RC8, v1.0.0RC9] but it does not match your minimum-stability.
``` 

Not really keen on changing the stability as it affects more than just this package, and we generally keep software as up-to-date as possible so jumping down a release isn't really feasible either.

Any suggestions?

Cheers

**Comment by hfig** [comment]
See #32. You can explicitly request a less stable version of a dependency without falling afoul of your whole package's ``minimum-stability`` ie

``composer require "pear/ole:^1.0.0RC8"``

You could also go and request ``pear/ole`` mark a stable release given the thing is decades old. From memory the only fixes and enhancements on that library in the past number of years have been requests/PRs from users of this library!
